-- Inventory ordering needs a private immutable insertion sequence, mirroring
-- the operation history sequence from 000005. The C collation makes the
-- equal-created-time backfill independent of database locale; created_at_ns
-- stays honest public data and is never rewritten.
ALTER TABLE resources
    ADD COLUMN resource_seq bigint GENERATED BY DEFAULT AS IDENTITY;

WITH ordered AS (
    SELECT id, row_number() OVER (ORDER BY created_at_ns ASC, id COLLATE "C" ASC) AS resource_seq
    FROM resources
)
UPDATE resources AS resource
SET resource_seq = ordered.resource_seq
FROM ordered
WHERE resource.id = ordered.id;

SELECT setval(
    pg_get_serial_sequence('resources', 'resource_seq'),
    COALESCE(MAX(resource_seq), 1),
    MAX(resource_seq) IS NOT NULL
)
FROM resources;

ALTER TABLE resources
    ALTER COLUMN resource_seq SET GENERATED ALWAYS,
    ADD CONSTRAINT resources_resource_seq_positive CHECK (resource_seq > 0),
    ADD CONSTRAINT resources_resource_seq_unique UNIQUE (resource_seq);

CREATE INDEX resources_owner_sequence ON resources(owner_kind, owner_id, resource_seq DESC);

CREATE OR REPLACE FUNCTION liftr_protect_resource_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.id IS DISTINCT FROM NEW.id OR OLD.type_name IS DISTINCT FROM NEW.type_name OR OLD.type_version IS DISTINCT FROM NEW.type_version THEN
        RAISE EXCEPTION 'resource identity and type are immutable' USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF OLD.resource_seq IS DISTINCT FROM NEW.resource_seq THEN
        RAISE EXCEPTION 'resource sequence is immutable' USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    -- Ownership is fixed at creation: every authorization decision keys on
    -- the stored owner, so silent ownership edits would change access
    -- semantics behind existing Resources. Any future owner transfer must be
    -- an explicit workflow with its own migration (ADR-0016).
    IF OLD.owner_kind IS DISTINCT FROM NEW.owner_kind OR OLD.owner_id IS DISTINCT FROM NEW.owner_id THEN
        RAISE EXCEPTION 'resource owner is immutable' USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$;
