-- Milestone 21: resource relationships and dependency-aware lifecycle.
--
-- Adds:
--   * resource_desired_references  — the source's admitted dependency intent,
--     rewritten atomically per generation under the owner structural lock.
--   * resource_applied_references  — the protective evidence of what a
--     source durably converged on; advances ONLY inside the terminal-success
--     transaction that proves create/update success including required output
--     postconditions, and is released only when the source becomes Deleted.
--   * operation_dependency_waits   — private durable wait registrations that
--     bind one blocked Operation to exactly one blocking target.
--   * the WakeDependents outbox kind — versioned, resource-targeted wake work
--     with at most one active row per target for coalescing.

CREATE TABLE resource_desired_references (
    source_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    slot text NOT NULL CHECK (btrim(slot) <> ''),
    target_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    generation numeric(20,0) NOT NULL CHECK (generation > 0 AND generation <= 18446744073709551615),
    PRIMARY KEY (source_id, slot, target_id),
    CHECK (source_id <> target_id)
);

CREATE INDEX resource_desired_refs_inbound
    ON resource_desired_references(target_id);
CREATE INDEX resource_desired_refs_source_gen
    ON resource_desired_references(source_id, generation);

CREATE TABLE resource_applied_references (
    source_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    slot text NOT NULL CHECK (btrim(slot) <> ''),
    target_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    generation numeric(20,0) NOT NULL CHECK (generation > 0 AND generation <= 18446744073709551615),
    PRIMARY KEY (source_id, slot, target_id),
    CHECK (source_id <> target_id)
);

CREATE INDEX resource_applied_refs_inbound
    ON resource_applied_references(target_id);

CREATE TABLE operation_dependency_waits (
    operation_id text NOT NULL REFERENCES operations(id) ON DELETE RESTRICT,
    target_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    wait_seq bigint GENERATED BY DEFAULT AS IDENTITY,
    operation_version numeric(20,0) NOT NULL CHECK (operation_version > 0 AND operation_version <= 18446744073709551615),
    registered_target_version numeric(20,0) NOT NULL CHECK (registered_target_version > 0 AND registered_target_version <= 18446744073709551615),
    PRIMARY KEY (operation_id, target_id)
);
-- Identity sequences are non-transactional in PostgreSQL; mirror the
-- operations/resources convention so rolled-back admissions consume values.
SELECT setval(pg_get_serial_sequence('operation_dependency_waits', 'wait_seq'),
    COALESCE((SELECT MAX(wait_seq) FROM operation_dependency_waits), 1));

-- Deliberately NO standalone unique index on wait_seq: the IDENTITY column is
-- already unique, and a second btree on wait_seq alone misleads the planner
-- into serving the hot keyset fanout query (target_id = $1 AND wait_seq > $2
-- ORDER BY wait_seq) with an index that degrades badly whenever one target's
-- waiters are sparse across the global sequence space. The composite index
-- below is the single intended access path.
CREATE INDEX operation_dependency_waits_by_target
    ON operation_dependency_waits(target_id, wait_seq);

-- Extend the outbox kind vocabulary and targeting rules for WakeDependents.
-- The original checks were created unnamed in 000001; drop every table-level
-- check constraint that references `kind` by catalog lookup, then re-add them
-- with explicit names so this migration is deterministic across databases.
DO $$
DECLARE constraint_name text;
BEGIN
    FOR constraint_name IN
        SELECT c.conname
        FROM pg_constraint c
        WHERE c.conrelid = 'outbox_messages'::regclass
          AND c.contype = 'c'
          AND pg_get_constraintdef(c.oid) LIKE '%kind%'
    LOOP
        EXECUTE format('ALTER TABLE outbox_messages DROP CONSTRAINT %I', constraint_name);
    END LOOP;
END $$;

ALTER TABLE outbox_messages ADD CONSTRAINT outbox_kind_vocabulary
    CHECK (kind IN ('Drive', 'Dispatch', 'Observe', 'PassiveObserve', 'WakeDependents'));
ALTER TABLE outbox_messages ADD CONSTRAINT outbox_kind_targeting
    CHECK (
        ((kind IN ('Drive', 'Dispatch', 'Observe')) AND operation_id IS NOT NULL AND resource_id IS NULL) OR
        ((kind IN ('PassiveObserve', 'WakeDependents')) AND operation_id IS NULL AND resource_id IS NOT NULL)
    );

-- At most one ACTIVE wake per target: concurrent transitions coalesce behind
-- the single active row, and its finalizer's version handshake guarantees no
-- later gate-relevant change is lost. Completed/Dead rows are exempt so the
-- VERSIONED dedupe key can be minted fresh forever.
CREATE UNIQUE INDEX outbox_one_active_wake_per_resource
    ON outbox_messages(resource_id) WHERE kind = 'WakeDependents' AND state IN ('Pending', 'Leased');
