-- Existing history receives a deterministic oldest-to-newest sequence. The C
-- collation makes equal-request-time backfill independent of database locale.
ALTER TABLE operations
    ADD COLUMN operation_seq bigint GENERATED BY DEFAULT AS IDENTITY;

WITH ordered AS (
    SELECT id, row_number() OVER (ORDER BY requested_at_ns ASC, id COLLATE "C" ASC) AS operation_seq
    FROM operations
)
UPDATE operations AS operation
SET operation_seq = ordered.operation_seq
FROM ordered
WHERE operation.id = ordered.id;

SELECT setval(
    pg_get_serial_sequence('operations', 'operation_seq'),
    COALESCE(MAX(operation_seq), 1),
    MAX(operation_seq) IS NOT NULL
)
FROM operations;

ALTER TABLE operations
    ALTER COLUMN operation_seq SET GENERATED ALWAYS,
    ADD CONSTRAINT operations_operation_seq_positive CHECK (operation_seq > 0),
    ADD CONSTRAINT operations_operation_seq_unique UNIQUE (operation_seq),
    ADD COLUMN retry_of_operation_id text COLLATE "C",
    ADD CONSTRAINT operations_retry_not_self CHECK (retry_of_operation_id IS NULL OR retry_of_operation_id <> id),
    ADD CONSTRAINT operations_retry_matching_intent
        FOREIGN KEY (retry_of_operation_id, resource_id, capability, target_generation)
        REFERENCES operations(id, resource_id, capability, target_generation) ON DELETE RESTRICT;

DROP INDEX operations_resource_created;
CREATE INDEX operations_resource_sequence ON operations(resource_id, operation_seq DESC);

CREATE FUNCTION liftr_validate_operation_retry() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    source_state text;
BEGIN
    IF NEW.retry_of_operation_id IS NOT NULL THEN
        SELECT state INTO source_state FROM operations WHERE id = NEW.retry_of_operation_id;
        IF source_state IS DISTINCT FROM 'Failed' THEN
            RAISE EXCEPTION 'retry source operation must be failed' USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER operation_retry_source_is_failed
    BEFORE INSERT OR UPDATE OF retry_of_operation_id ON operations
    FOR EACH ROW EXECUTE FUNCTION liftr_validate_operation_retry();

CREATE OR REPLACE FUNCTION liftr_protect_operation_intent() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.state IN ('Succeeded', 'Failed', 'Canceled') THEN
            RAISE EXCEPTION 'terminal operation is immutable' USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.state IN ('Succeeded', 'Failed', 'Canceled') AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'terminal operation is immutable' USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF OLD.id IS DISTINCT FROM NEW.id OR OLD.resource_id IS DISTINCT FROM NEW.resource_id OR
       OLD.capability IS DISTINCT FROM NEW.capability OR OLD.target_generation IS DISTINCT FROM NEW.target_generation OR
       OLD.requested_at_ns IS DISTINCT FROM NEW.requested_at_ns OR OLD.operation_seq IS DISTINCT FROM NEW.operation_seq OR
       OLD.retry_of_operation_id IS DISTINCT FROM NEW.retry_of_operation_id THEN
        RAISE EXCEPTION 'operation intent is immutable' USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER operation_intent_is_immutable ON operations;
CREATE TRIGGER operation_intent_is_immutable
    BEFORE UPDATE OR DELETE ON operations FOR EACH ROW EXECUTE FUNCTION liftr_protect_operation_intent();
