// SPDX-License-Identifier: Apache-2.0

package httpapi_test

import (
	"net/http"
	"testing"

	apihttp "github.com/sithea-nou/liftr/internal/api/http"
)

// TestRequestIDIsAlwaysAuthoritative pins that X-Request-ID is generated by
// the server on every response and never taken from client input, while an
// optional X-Correlation-ID stays strictly separate.
func TestRequestIDIsAlwaysAuthoritative(t *testing.T) {
	f := newFixture(t)

	first := f.request(t, http.MethodGet, "/healthz", nil, nil)
	firstID := header(first, "X-Request-ID")
	if firstID == "" {
		t.Fatal("every response must carry a server-generated X-Request-ID")
	}

	second := f.request(t, http.MethodGet, "/healthz", map[string]string{"X-Request-ID": "client-forged-id"}, nil)
	if got := header(second, "X-Request-ID"); got == "client-forged-id" || got == "" {
		t.Fatalf("client-supplied X-Request-ID must not become authoritative (got %q)", got)
	}
	if header(second, "X-Request-ID") == firstID {
		t.Fatal("request IDs must be unique per request")
	}

	correlated := f.request(t, http.MethodGet, "/healthz", map[string]string{"X-Correlation-ID": "trace-42"}, nil)
	if got := header(correlated, "X-Correlation-ID"); got != "trace-42" {
		t.Fatalf("X-Correlation-ID = %q, want verbatim echo", got)
	}
	requestID := header(correlated, "X-Request-ID")
	if requestID == "trace-42" || requestID == "" {
		t.Fatalf("correlation ID leaked into request identity: %q", requestID)
	}
}

// TestProblemCarriesAuthoritativeRequestID ties Problem responses to the
// authoritative transport identifier.
func TestProblemCarriesAuthoritativeRequestID(t *testing.T) {
	f := newFixture(t)
	response := f.request(t, http.MethodGet, "/v1/resources/missing", map[string]string{"X-Correlation-ID": "trace-99"}, nil)
	document := expectProblem(t, response, http.StatusNotFound, "RESOURCE_NOT_FOUND")
	if document["requestId"] != header(response, "X-Request-ID") {
		t.Fatalf("problem requestId %v does not match response X-Request-ID %q", document["requestId"], header(response, "X-Request-ID"))
	}
	if document["instance"] != "/v1/resources/missing" {
		t.Fatalf("problem instance = %v", document["instance"])
	}
}

// Without any authenticator the versioned surface fails closed: every
// request is answered UNAUTHENTICATED rather than exposing whether a service
// exists behind it (ADR-0012).
func TestVersionedEndpointsWithoutAuthenticatorFailClosed(t *testing.T) {
	handler := apihttp.NewHandler(apihttp.Deps{})
	f := &fixture{handler: handler}

	getResource := f.request(t, http.MethodGet, "/v1/resources/r1", nil, nil)
	expectProblem(t, getResource, http.StatusUnauthorized, "UNAUTHENTICATED")

	createBody := map[string]any{
		"id":   "r1",
		"type": map[string]string{"name": testResourceType, "version": testResourceVersion},
		"owner": map[string]string{
			"kind": "team",
			"id":   "platform",
		},
		"spec": map[string]any{},
	}
	create := f.request(t, http.MethodPost, "/v1/resources", map[string]string{"Idempotency-Key": "k"}, createBody)
	expectProblem(t, create, http.StatusUnauthorized, "UNAUTHENTICATED")

	getOperation := f.request(t, http.MethodGet, "/v1/operations/op-1", nil, nil)
	expectProblem(t, getOperation, http.StatusUnauthorized, "UNAUTHENTICATED")

	readyz := f.request(t, http.MethodGet, "/readyz", nil, nil)
	expectProblem(t, readyz, http.StatusServiceUnavailable, "PERSISTENCE_UNAVAILABLE")

	healthz := f.request(t, http.MethodGet, "/healthz", nil, nil)
	expectStatus(t, healthz, http.StatusOK)
}
